# Generated by Django 3.2.6 on 2021-08-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210806_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='seed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
