# Generated by Django 3.2.6 on 2021-08-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_device_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
