# Generated by Django 3.2.6 on 2021-08-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_qrcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='otp',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
