# Generated by Django 3.2.6 on 2021-08-08 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_totop_authenticate_totp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qrcodes',
        ),
    ]
